name: Stop scheduled job

on:
  # Triggers the workflow every monday at 16:30 UTC
  schedule:
    - cron: "10 03 * * thu"

jobs:
  cron:
    runs-on: ubuntu-latest
    name: Stop the server
    steps:
      - name: Download RunPod CLI
        run: wget https://github.com/Run-Pod/runpodctl/releases/download/v1.5.0/runpodctl-linux-amd && chmod +x runpodctl-linux-amd
      - name: Start Pod
        run: ./runpodctl-linux-amd config --apiKey=${{secrets.RUN_POD_API_KEY}} && ./runpodctl-linux-amd stop pod llr8joxw2qhxbi

